resources:
- name: AspNetCoreSite
  type: git
  source:
    uri: 
    branch: master

jobs:
- name: aspnetcore-hello-world-app
  plan:
  - get: AspNetCoreSite
    trigger: true
  - task: tests
    file: AspNetCoreSite/ci/build.yml
